import React, { forwardRef, useEffect, useState, useContext, useMemo, useRef, useCallback, createContext } from 'react';
import PropTypes from 'prop-types';
import { Box, Image, PortalManager, Text, Heading } from "@chakra-ui/react";
import { Unity } from "react-unity-webgl";
import { useUnity } from "./providers/UnityProvider";
import { useSendUnityEvent, useUnityOnFirstSceneLoaded, useUnityOnRequestUser, useUnityOnNameplateClick } from "./hooks/unityEvents";
import { useFadeStyles } from "./hooks/useFadeStyles";
import { EventNames, eventBus } from '@disruptive-spaces/shared/events/EventBus';
import { Logger } from '@disruptive-spaces/shared/logging/react-log';
import { UserContext } from '@disruptive-spaces/shared/providers/UserProvider';
import { getUserProfileData } from '@disruptive-spaces/shared/firebase/userFirestore';
import TestModalTrigger from "./components/TestModalTrigger";
import LoaderProgress from "./components/Loader/LoaderProgress";
import AuthenticationButton from "./components/AuthenticationButton";
import HelpButton from "./components/HelpButton";
import ProfileButton from "./components/ProfileButton";
import FullScreenButton from "./components/FullScreenButton";
import SendThumbnailUrlToUnity from "./components/EventTests/SendThumbnailUrlToUnity";
import VideoPlayer from "./components/VideoPlayer";
import { useFullscreenContext } from '@disruptive-spaces/shared/providers/FullScreenProvider';
import NameplateModal from "./components/NameplateModal";
import UnityPlayerList from "./components/UnityPlayerList";
import { CanvasMainMenu } from "./components/CanvasMainMenu";
import { useUnityPlayerList } from "./hooks/unityEvents/useUnityPlayerList";
import { AgoraProvider, VoiceButton, ScreenShareDisplay, useVoiceChat, VoiceChatDebugPanel } from './voice-chat'; 